---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: clang-format
  name: clang-format
  entry: eckphi/docker-pre-commit-hooks:latest clang-format-hook
  description: Formats C, C++, Objective-C, and Java code
  types_or: [c, c++, c#, objective-c, java]
  language: docker_image
- id: clang-tidy
  name: clang-tidy
  entry: eckphi/docker-pre-commit-hooks:latest clang-tidy-hook
  description: Find warnings/errors in C, C++, and Objective-C code
  types_or: [c, c++, c#, objective-c]
  language: docker_image
- id: oclint
  name: oclint
  entry: eckphi/docker-pre-commit-hooks:latest oclint-hook
  description: Find warnings/errors in C, C++, and Objective-C code
  types_or: [c, c++, c#, objective-c]
  language: docker_image
- id: uncrustify
  name: uncrustify
  entry: eckphi/docker-pre-commit-hooks:latest uncrustify-hook
  description: Formats C, C++, Objective-C, Java, D, and Vala code
  # D, vala currently aren't valid file types. See https://github.com/pre-commit/identify/issues/258
  types_or: [c, c++, c#, objective-c, java]
  language: docker_image
- id: cppcheck
  name: cppcheck
  entry: eckphi/docker-pre-commit-hooks:latest cppcheck-hook
  description: Find warnings/errors in C, C++, and Objective-C code
  types_or: [c, c++, c#, objective-c]
  language: docker_image
- id: cpplint
  name: cpplint
  entry: eckphi/docker-pre-commit-hooks:latest cpplint-hook
  description: Find warnings/errors in C/CPP code
  types_or:  [c, c++, c#, objective-c, cuda]
  language: docker_image
- id: include-what-you-use
  name: include-what-you-use
  entry: eckphi/docker-pre-commit-hooks:latest include-what-you-use-hook
  description: Runs Include-What-You-Use (iwyu) in C/CPP code
  types_or:  [c, c++, c#, objective-c, cuda]
  language: docker_image